name: First Workflow
on: workflow_dispatch
jobs:
  first-job: 
    runs-on: ubuntu-latest
    steps: 
      - name: Print greeting
        run: echo "Hello World!"
      - name: Print goodbye
        run: echo "Done."
  windows-job: 
    runs-on: windows-latest
    steps: 
      - name: Directory PowerShell
        run: Get-Location
      - name: Directory Bash
        run: pwd
        shell: bash
      - name: Checkout
        uses: actions/checkout@v1
